<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="WorkOrder">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="WorkOrder">
					<xs:complexType>
						<xs:sequence>
							<xs:element nillable="true" minOccurs="0"
								maxOccurs="unbounded" name="workOrderId">
								<xs:simpleType>
									<xs:restriction base="xs:string"
										xmlns="">
										<xs:maxLength value="100" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element nillable="false"
								maxOccurs="1" name="workOrderName" minOccurs="1" type="xs:string">
							</xs:element>
							<xs:element nillable="true"
								name="effectiveStatus" minOccurs="1" maxOccurs="1" type="xs:string">
							</xs:element>
							<xs:element nillable="true"
								maxOccurs="1" name="workOrderOwnerId" type="xs:string" minOccurs="1">
							</xs:element>
							<xs:element nillable="true"
								maxOccurs="1" name="vendor" type="xs:string" minOccurs="1">
							</xs:element>
							<xs:element nillable="true"
								maxOccurs="1" name="statementOfWork" type="xs:string" minOccurs="1">
							</xs:element>
							<xs:element type="xs:dateTime"
								nillable="false" maxOccurs="1" name="endDate" xmlns="" minOccurs="1"/>
							<xs:element nillable="true" minOccurs="0"
								maxOccurs="unbounded" name="externalDailyRate" type="xs:string">
							</xs:element>
							<xs:element name="userSysId" minOccurs="1"
								maxOccurs="1" type="xs:string">
							</xs:element>
							<xs:element name="startDate"
								type="xs:dateTime" minOccurs="1" maxOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>